#!/usr/bin/env python3
from pathlib import Path
import json,hashlib,sys
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def jl(p):return [json.loads(x) for x in Path(p).read_text(encoding="utf-8").splitlines() if x.strip()]
root=Path(sys.argv[1]);cand=Path(sys.argv[2]);pr=Path(sys.argv[3]);ct=Path(sys.argv[4]);fails=[];checks=[]
def ck(cond,name,detail=None):checks.append({"check":name,"pass":bool(cond),"detail":detail});fails.append((name,detail)) if not cond else None
p=json.loads(pr.read_text());c=json.loads(ct.read_text());m=json.loads((cand/"MANIFEST.json").read_text());rows=jl(cand/"PREDICATE_IDENTIFYING_V12.token_reference.private.jsonl");ev=jl(cand/"PREDICATE_EVAL.private.jsonl")
ck(p["status"]=="FROZEN_BEFORE_ANY_V14_MODEL_OUTCOME","prereg_frozen");ck(len(rows)==72,"train_rows_72");ck(len(ev)==48,"eval_rows_48");ck(all(len(r["input_ids"])==len(r["loss_mask"]) for r in rows),"token_masks_aligned");ck(max(len(r["input_ids"]) for r in rows)<=217,"max_seq_le_v13_predicate_217",max(len(r["input_ids"]) for r in rows));ck(c["sequence"]["checkpoint_steps"]=={"H1":36,"H2":72,"H4":144},"checkpoint_steps_exact");ck(c["sequence"]["steps_per_epoch"]==9 and c["sequence"]["epochs"]==16,"horizon_math");ck(m["policy_training_examples"]==0 and m["composed_training_examples"]==0,"no_policy_or_composed");ck(all(sorted(m["schedules"][str(s)]["order"])==list(range(72)) for s in c["seeds"]),"all_schedules_permutations");ck(len({m["schedules"][str(s)]["sha256"] for s in c["seeds"]})==6,"fresh_seed_orders_distinct");ck(sha(cand/"PREDICATE_IDENTIFYING_V12.token_reference.private.jsonl")==p["shared_experience"]["source_token_reference_sha256"],"tokenref_exact_inherited");ck(sha(cand/"PREDICATE_EVAL.private.jsonl")==p["shared_experience"]["eval_sha256"],"eval_exact_inherited");out={"schema":"cfe.v14.predicate-horizon-static-hostile.v1","status":"PASS_CANDIDATE__NOT_LOCKED__NOT_TRAINED" if not fails else "FAIL","check_count":len(checks),"failures":fails,"checks":checks,"laws":["SAME TRAJECTORY != SEPARATE INITIALIZATIONS","MORE EXPOSURE != MORE FIELD RESOLUTION","STATIC PASS != SCIENTIFIC EFFECT"]};op=root/"state/qualification/V14_PREDICATE_HORIZON_STATIC_HOSTILE_2026-08-31.json";op.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n");print(json.dumps(out,indent=2,sort_keys=True));sys.exit(1 if fails else 0)
