#!/usr/bin/env python3
from pathlib import Path
import argparse,json,hashlib,py_compile
def H(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def L(p):return json.loads(Path(p).read_text(encoding="utf-8-sig"))
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--root",type=Path,required=True);ap.add_argument("--lock",type=Path,required=True);ap.add_argument("--host-lock",type=Path,required=True);ap.add_argument("--profile-lock",type=Path,required=True);ap.add_argument("--repeatability",type=Path,required=True);ap.add_argument("--static",type=Path,required=True);ap.add_argument("--baseline",type=Path,required=True);ap.add_argument("--contract",type=Path,required=True);ap.add_argument("--prereg",type=Path,required=True);ap.add_argument("--out",type=Path,required=True);a=ap.parse_args();root=a.root.resolve();lock=L(a.lock);host=L(a.host_lock);prof=L(a.profile_lock);rep=L(a.repeatability);st=L(a.static);base=L(a.baseline);ct=L(a.contract);pre=L(a.prereg);checks=[];fails=[]
 def ck(x,n,d=None):checks.append({"check":n,"pass":bool(x),"detail":d});fails.append((n,d)) if not x else None
 ck(lock["status"]=="LOCKED_PRE_RUNTIME__NO_V14_SCIENTIFIC_TRAINING","lock_status");ck(host["status"]=="HOST_REVERIFIED__TOKENIZER_REPLAY_PASS__PROFILE_REPEATABILITY_PENDING","host_status");ck(host["runtime_tokenizer_exact_match"],"tokenizer_exact");ck(rep["status"]=="REPEATABILITY_PASS","repeatability_pass");ck(prof["status"]=="PROFILE_INHERITED_AND_V14_REPEATABILITY_QUALIFIED","profile_lock_status");ck(st["status"].startswith("PASS"),"static_status");ck(base["screen_admitted"],"baseline_headroom_admitted");ck(H(a.prereg)==ct["bindings"]["preregistration_sha256"],"contract_prereg_binding");ck(H(root/"state/candidates/v14_predicate_horizon_20260831/MANIFEST.json")==ct["bindings"]["candidate_manifest_sha256"],"contract_candidate_binding");ck(not any(root.glob("state/analysis/V14R_PREDICATE_HORIZON_CAMPAIGN_*")),"no_v14r_campaign_exists")
 for rel in ["tools/v14_predicate_horizon_common.py","tools/train_v14_predicate_horizon.py","tools/evaluate_v14_predicate_horizon.py","tools/run_v14_predicate_horizon_campaign.py"]:
  try:py_compile.compile(str(root/rel),doraise=True);ck(True,"compile_"+Path(rel).name)
  except Exception as e:ck(False,"compile_"+Path(rel).name,str(e))
 out={"schema":"cfe.v14r.predicate-horizon-preexecution.v1","status":"V14_RUNTIME_QUALIFIED__SCIENTIFIC_TRAINING_AUTHORIZED" if not fails else "BLOCKED","authorization_scope":"six fresh predicate-only trajectories with fixed H1/H2/H4 checkpoints","scientific_difference":"developmental horizon only","bindings":{"input_lock_sha256":H(a.lock),"host_lock_sha256":H(a.host_lock),"profile_lock_sha256":H(a.profile_lock),"repeatability_qualification_sha256":H(a.repeatability),"static_qualification_sha256":H(a.static),"baseline_inheritance_sha256":H(a.baseline),"training_contract_sha256":H(a.contract),"preregistration_sha256":H(a.prereg)},"checks":checks,"failures":fails,"hard_stop":"Any locked-byte/runtime identity drift requires new qualification before training."};a.out.parent.mkdir(parents=True,exist_ok=True);a.out.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n");print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(1 if fails else 0)
if __name__=="__main__":main()
